export const STORE_SKU_LIST = "STORE_SKU_LIST";
export const CLEAR_SKU_LIST = "CLEAR_SKU_LIST";
export const STORE_SKU_SEARCH_PARAMS = "STORE_SKU_SEARCH_PARAMS";
export const CLEAR_SKU_SEARCH_PARAMS = "CLEAR_SKU_SEARCH_PARAMS";